// <auto-generated />
namespace Vagents.Info.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FullDbConfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullDbConfig));
        
        string IMigrationMetadata.Id
        {
            get { return "201612120322546_FullDbConfig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
